/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponse } from './loginResponse';
import type { ErrorResponse } from './errorResponse';

export type AuthLogin200 = LoginResponse | ErrorResponse;
