/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */
import type { EmptyResponse } from './emptyResponse';
import type { ErrorResponse } from './errorResponse';

export type AuthLogout200 = EmptyResponse | ErrorResponse;
