/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthCheckResponse } from './authCheckResponse';
import type { ErrorResponse } from './errorResponse';

export type AuthCheck200 = AuthCheckResponse | ErrorResponse;
