/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface BuildInfoBuildInfo {
  buildTime: string;
  gitCommit: string;
  gitShortCommit: string;
  gitBranch: string;
  gitTag?: string;
  githubUrl: string;
}
