/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateEntryResponse {
  /** The path of the created entry */
  path: string;
}
