/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateEntryRequest {
  /** The title of the new entry */
  title?: string;
}
