/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface EntryWithDestTitle {
  path: string;
  title: string;
  body: string;
  visibility: string;
  format: string;
  /** @nullable */
  imageUrl?: string | null;
  dstTitle: string;
}
