/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Object where keys are lowercase destination entry titles and values are their paths (null if entry doesn't exist)..
 */
export interface LinkedEntryPathsResponse {[key: string]: string}
