/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginRequest {
  username: string;
  password: string;
  remember_me?: boolean;
}
