/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */
import type { EntryWithDestTitle } from './entryWithDestTitle';
import type { EntryWithImage } from './entryWithImage';

export interface TwoHopLink {
  src: EntryWithDestTitle;
  links: EntryWithImage[];
}
