/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateEntryBodyRequest {
  /** The new content of the entry */
  body: string;
}
