/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateEntryTitleRequest {
  /** The new title for the entry */
  title: string;
}
