/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateVisibilityResponse {
  /** The new visibility status for the entry */
  visibility: string;
}
