repos:
  - repo: local
    hooks:
      - id: goimports
        name: goimports
        entry: goimports -w -local github.com/tokuhirom/blog4
        language: system
        types: [go]
        pass_filenames: true
      - id: go-fmt
        name: go fmt
        entry: go fmt
        language: system
        types: [go]
        pass_filenames: true
      - id: go-vet
        name: go vet
        entry: go vet
        language: system
        types: [go]
        pass_filenames: false