FROM golang:1.25.5-trixie

# Install dependencies
RUN apt-get update && apt-get install -y mariadb-client && \
    rm -rf /var/lib/apt/lists/*

# Install air for hot-reload
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8181

CMD ["air"]