version: '3'

interval: 500ms

tasks:
  sqlc-admin:
    cmds:
      - go tool sqlc generate -f ./db/admin/sqlc-admin.yml
    sources:
      - ./db/admin/sqlc-admin.yml
      - ./db/admin/queries/admin.sql
      - ./db/admin/queries/visibility.sql
      - ./db/schema.sql
    generates:
      - ./db/admin/admindb/db.go
      - ./db/admin/admindb/models.go
      - ./db/admin/admindb/public.sql.go
    desc: "Generate SQLC code for admin database"

  sqlc-public:
    cmds:
      - go tool sqlc generate -f ./db/public/sqlc-public.yml
    sources:
      - ./db/public/sqlc-public.yml
      - ./db/public/queries/**/*.sql
      - ./db/schema.sql
    generates:
      - ./db/public/publicdb/db.go
      - ./db/public/publicdb/models.go
      - ./db/public/publicdb/public.sql.go
    desc: "Generate SQLC code"

  sqlc:
    deps: [sqlc-admin, sqlc-public]
    desc: "Run SQLC generation for both admin and public databases"

  gen:
    deps: [sqlc]
    desc: "Generate all code (SQLC only)"

  docker-build:
    cmds:
      - docker build -t blog4 .
    sources:
      - Dockerfile
    desc: "Build production Docker image"

