version: '3'

tasks:
  frontend:
    cmds:
      - npm run dev
    dir: ./server/admin/frontend
    desc: "Run the Node.js development server"

  frontend-build:
    cmds:
      - npm run build
    dir: ./server/admin/frontend
    sources:
      - ./server/admin/frontend/package.json
      - ./server/admin/frontend/package-lock.json
      - ./server/admin/frontend/tsconfig.json
      - ./server/admin/frontend/src/**/*
    desc: "Build the frontend"

  sqlc-admin:
    cmds:
      - sqlc generate -f ./db/admin/sqlc-admin.yml
    sources:
      - ./db/admin/sqlc-admin.yml
      - ./db/admin/queries/**/*.sql
      - ./db/schema.sql
    generates:
      - ./db/admin/admindb/db.go
      - ./db/admin/admindb/models.go
      - ./db/admin/admindb/public.sql.go
    desc: "Generate SQLC code for admin database"

  sqlc-public:
    cmds:
      - sqlc generate -f ./db/public/sqlc-public.yml
    sources:
      - ./db/public/sqlc-public.yml
      - ./db/public/queries/**/*.sql
      - ./db/schema.sql
    generates:
      - ./db/public/publicdb/db.go
      - ./db/public/publicdb/models.go
      - ./db/public/publicdb/public.sql.go
    desc: "Generate SQLC code"

  sqlc:
    deps: [sqlc-admin, sqlc-public]
    desc: "Run SQLC generation for both admin and public databases"

  dev:
    deps: [sqlc, frontend, frontend-build, ogen]
    desc: "Run both SQLC generation and Node.js dev server"

  ogen:
    cmds:
      - go generate main.go
    sources:
      - oepnapi.yml
      - main.go
    desc: "Generate OpenAPI server code"
