// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package admindb

import (
	"context"
	"database/sql"
)

type Querier interface {
	AdminGetEntryByPath(ctx context.Context, path string) (AdminGetEntryByPathRow, error)
	CountAmazonCacheByAsin(ctx context.Context, asin string) (int64, error)
	CreateEmptyEntry(ctx context.Context, arg CreateEmptyEntryParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	DeleteEntry(ctx context.Context, path string) (int64, error)
	DeleteEntryImageByPath(ctx context.Context, path string) (int64, error)
	DeleteEntryLinkByPath(ctx context.Context, srcPath string) (int64, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, sessionID string) error
	GetAllEntryTitles(ctx context.Context) ([]string, error)
	GetAmazonImageUrlByAsin(ctx context.Context, asin string) (sql.NullString, error)
	GetEntriesByLinkedTitle(ctx context.Context, dstTitle string) ([]Entry, error)
	GetEntryImageNotProcessedEntries(ctx context.Context) ([]Entry, error)
	GetEntryVisibility(ctx context.Context, path string) (GetEntryVisibilityRow, error)
	GetLatestEntries(ctx context.Context, arg GetLatestEntriesParams) ([]GetLatestEntriesRow, error)
	GetLinkedEntries(ctx context.Context, srcPath string) ([]GetLinkedEntriesRow, error)
	GetSession(ctx context.Context, sessionID string) (AdminSession, error)
	InsertAmazonProductDetail(ctx context.Context, arg InsertAmazonProductDetailParams) (int64, error)
	InsertEntryImage(ctx context.Context, arg InsertEntryImageParams) (int64, error)
	// TODO batch insert
	InsertEntryLink(ctx context.Context, arg InsertEntryLinkParams) (int64, error)
	UpdateEntryBody(ctx context.Context, arg UpdateEntryBodyParams) (int64, error)
	UpdateEntryTitle(ctx context.Context, arg UpdateEntryTitleParams) (int64, error)
	UpdatePublishedAt(ctx context.Context, path string) error
	UpdateSessionLastAccessed(ctx context.Context, sessionID string) error
	UpdateVisibility(ctx context.Context, arg UpdateVisibilityParams) error
}

var _ Querier = (*Queries)(nil)
