/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin API
 * OpenAPI spec version: 1.0.0
 */

export type GetLatestEntriesParams = {
/**
 * Filter entries by the last edited date
 */
last_last_edited_at?: string;
};
