// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateEntry implements createEntry operation.
//
// Create a new entry.
//
// POST /entries
func (UnimplementedHandler) CreateEntry(ctx context.Context, req *CreateEntryRequest) (r CreateEntryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEntry implements deleteEntry operation.
//
// Delete an entry.
//
// DELETE /entries/{path}
func (UnimplementedHandler) DeleteEntry(ctx context.Context, params DeleteEntryParams) (r DeleteEntryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllEntryTitles implements getAllEntryTitles operation.
//
// Get all entry titles.
//
// GET /entries/titles
func (UnimplementedHandler) GetAllEntryTitles(ctx context.Context) (r GetAllEntryTitlesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEntryByDynamicPath implements getEntryByDynamicPath operation.
//
// Get entry by dynamic path.
//
// GET /entries/{path}
func (UnimplementedHandler) GetEntryByDynamicPath(ctx context.Context, params GetEntryByDynamicPathParams) (r GetEntryByDynamicPathRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLatestEntries implements getLatestEntries operation.
//
// Get latest entries.
//
// GET /entries
func (UnimplementedHandler) GetLatestEntries(ctx context.Context, params GetLatestEntriesParams) (r GetLatestEntriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLinkPallet implements getLinkPallet operation.
//
// Get linked entry paths.
//
// GET /entries/{path}/link-pallet
func (UnimplementedHandler) GetLinkPallet(ctx context.Context, params GetLinkPalletParams) (r GetLinkPalletRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLinkedEntryPaths implements getLinkedEntryPaths operation.
//
// Get linked entry paths.
//
// GET /entries/{path}/linked-paths
func (UnimplementedHandler) GetLinkedEntryPaths(ctx context.Context, params GetLinkedEntryPathsParams) (r GetLinkedEntryPathsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegenerateEntryImage implements regenerateEntryImage operation.
//
// Regenerate entry image.
//
// POST /entries/{path}/regenerate-image
func (UnimplementedHandler) RegenerateEntryImage(ctx context.Context, params RegenerateEntryImageParams) (r RegenerateEntryImageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEntryBody implements updateEntryBody operation.
//
// Update entry body.
//
// PUT /entries/{path}/body
func (UnimplementedHandler) UpdateEntryBody(ctx context.Context, req *UpdateEntryBodyRequest, params UpdateEntryBodyParams) (r UpdateEntryBodyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEntryTitle implements updateEntryTitle operation.
//
// Update entry title.
//
// PUT /entries/{path}/title
func (UnimplementedHandler) UpdateEntryTitle(ctx context.Context, req *UpdateEntryTitleRequest, params UpdateEntryTitleParams) (r UpdateEntryTitleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEntryVisibility implements updateEntryVisibility operation.
//
// Update entry visibility.
//
// POST /admin/api/entry/{path}/visibility
func (UnimplementedHandler) UpdateEntryVisibility(ctx context.Context, req *UpdateVisibilityRequest, params UpdateEntryVisibilityParams) (r UpdateEntryVisibilityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadPost implements POST /upload operation.
//
// POST /upload
func (UnimplementedHandler) UploadPost(ctx context.Context, req *UploadPostReq) (r *UploadFileResponse, _ error) {
	return r, ht.ErrNotImplemented
}
