// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetEntryByDynamicPath implements getEntryByDynamicPath operation.
//
// Get entry by dynamic path.
//
// GET /entries/{path}
func (UnimplementedHandler) GetEntryByDynamicPath(ctx context.Context, params GetEntryByDynamicPathParams) (r *GetLatestEntriesRow, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLatestEntries implements getLatestEntries operation.
//
// Get latest entries.
//
// GET /entries
func (UnimplementedHandler) GetLatestEntries(ctx context.Context, params GetLatestEntriesParams) (r []GetLatestEntriesRow, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLinkedEntryPaths implements getLinkedEntryPaths operation.
//
// Get linked entry paths.
//
// GET /entries/{path}/links
func (UnimplementedHandler) GetLinkedEntryPaths(ctx context.Context, params GetLinkedEntryPathsParams) (r LinkedEntriesResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEntryBody implements updateEntryBody operation.
//
// Update entry body.
//
// PUT /entries/{path}/body
func (UnimplementedHandler) UpdateEntryBody(ctx context.Context, req *UpdateEntryBodyRequest, params UpdateEntryBodyParams) (r UpdateEntryBodyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEntryTitle implements updateEntryTitle operation.
//
// Update entry title.
//
// PUT /entries/{path}/title
func (UnimplementedHandler) UpdateEntryTitle(ctx context.Context, req *UpdateEntryTitleRequest, params UpdateEntryTitleParams) (r UpdateEntryTitleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
