// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetLatestEntriesOperation OperationName = "GetLatestEntries"
)
