// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateEntry implements createEntry operation.
	//
	// Create a new entry.
	//
	// POST /entries
	CreateEntry(ctx context.Context, req *CreateEntryRequest) (CreateEntryRes, error)
	// DeleteEntry implements deleteEntry operation.
	//
	// Delete an entry.
	//
	// DELETE /entries/{path}
	DeleteEntry(ctx context.Context, params DeleteEntryParams) (DeleteEntryRes, error)
	// GetAllEntryTitles implements getAllEntryTitles operation.
	//
	// Get all entry titles.
	//
	// GET /entries/titles
	GetAllEntryTitles(ctx context.Context) (GetAllEntryTitlesRes, error)
	// GetEntryByDynamicPath implements getEntryByDynamicPath operation.
	//
	// Get entry by dynamic path.
	//
	// GET /entries/{path}
	GetEntryByDynamicPath(ctx context.Context, params GetEntryByDynamicPathParams) (GetEntryByDynamicPathRes, error)
	// GetLatestEntries implements getLatestEntries operation.
	//
	// Get latest entries.
	//
	// GET /entries
	GetLatestEntries(ctx context.Context, params GetLatestEntriesParams) (GetLatestEntriesRes, error)
	// GetLinkPallet implements getLinkPallet operation.
	//
	// Get linked entry paths.
	//
	// GET /entries/{path}/link-pallet
	GetLinkPallet(ctx context.Context, params GetLinkPalletParams) (GetLinkPalletRes, error)
	// GetLinkedEntryPaths implements getLinkedEntryPaths operation.
	//
	// Get linked entry paths.
	//
	// GET /entries/{path}/linked-paths
	GetLinkedEntryPaths(ctx context.Context, params GetLinkedEntryPathsParams) (GetLinkedEntryPathsRes, error)
	// RegenerateEntryImage implements regenerateEntryImage operation.
	//
	// Regenerate entry image.
	//
	// POST /entries/{path}/regenerate-image
	RegenerateEntryImage(ctx context.Context, params RegenerateEntryImageParams) (RegenerateEntryImageRes, error)
	// UpdateEntryBody implements updateEntryBody operation.
	//
	// Update entry body.
	//
	// PUT /entries/{path}/body
	UpdateEntryBody(ctx context.Context, req *UpdateEntryBodyRequest, params UpdateEntryBodyParams) (UpdateEntryBodyRes, error)
	// UpdateEntryTitle implements updateEntryTitle operation.
	//
	// Update entry title.
	//
	// PUT /entries/{path}/title
	UpdateEntryTitle(ctx context.Context, req *UpdateEntryTitleRequest, params UpdateEntryTitleParams) (UpdateEntryTitleRes, error)
	// UpdateEntryVisibility implements updateEntryVisibility operation.
	//
	// Update entry visibility.
	//
	// POST /admin/api/entry/{path}/visibility
	UpdateEntryVisibility(ctx context.Context, req *UpdateVisibilityRequest, params UpdateEntryVisibilityParams) (UpdateEntryVisibilityRes, error)
	// UploadPost implements POST /upload operation.
	//
	// POST /upload
	UploadPost(ctx context.Context, req *UploadPostReq) (*UploadFileResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
