// Code generated by ogen, DO NOT EDIT.
package openapi

type AuthCheckRes interface {
	authCheckRes()
}

type AuthLoginRes interface {
	authLoginRes()
}

type AuthLogoutRes interface {
	authLogoutRes()
}

type CreateEntryRes interface {
	createEntryRes()
}

type DeleteEntryRes interface {
	deleteEntryRes()
}

type GetAllEntryTitlesRes interface {
	getAllEntryTitlesRes()
}

type GetEntryByDynamicPathRes interface {
	getEntryByDynamicPathRes()
}

type GetLatestEntriesRes interface {
	getLatestEntriesRes()
}

type GetLinkPalletRes interface {
	getLinkPalletRes()
}

type GetLinkedEntryPathsRes interface {
	getLinkedEntryPathsRes()
}

type RegenerateEntryImageRes interface {
	regenerateEntryImageRes()
}

type UpdateEntryBodyRes interface {
	updateEntryBodyRes()
}

type UpdateEntryTitleRes interface {
	updateEntryTitleRes()
}

type UpdateEntryVisibilityRes interface {
	updateEntryVisibilityRes()
}

type UploadFileRes interface {
	uploadFileRes()
}
