// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetEntryByDynamicPathOperation OperationName = "GetEntryByDynamicPath"
	GetLatestEntriesOperation      OperationName = "GetLatestEntries"
	GetLinkedEntryPathsOperation   OperationName = "GetLinkedEntryPaths"
	UpdateEntryBodyOperation       OperationName = "UpdateEntryBody"
	UpdateEntryTitleOperation      OperationName = "UpdateEntryTitle"
)
