// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateEntryOperation           OperationName = "CreateEntry"
	DeleteEntryOperation           OperationName = "DeleteEntry"
	GetAllEntryTitlesOperation     OperationName = "GetAllEntryTitles"
	GetEntryByDynamicPathOperation OperationName = "GetEntryByDynamicPath"
	GetLatestEntriesOperation      OperationName = "GetLatestEntries"
	GetLinkPalletOperation         OperationName = "GetLinkPallet"
	GetLinkedEntryPathsOperation   OperationName = "GetLinkedEntryPaths"
	RegenerateEntryImageOperation  OperationName = "RegenerateEntryImage"
	UpdateEntryBodyOperation       OperationName = "UpdateEntryBody"
	UpdateEntryTitleOperation      OperationName = "UpdateEntryTitle"
	UpdateEntryVisibilityOperation OperationName = "UpdateEntryVisibility"
	UploadFileOperation            OperationName = "UploadFile"
)
