// Code generated by ogen, DO NOT EDIT.
package openapi

type CreateEntryRes interface {
	createEntryRes()
}

type UpdateEntryBodyRes interface {
	updateEntryBodyRes()
}

type UpdateEntryTitleRes interface {
	updateEntryTitleRes()
}
