// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"
	"time"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// GetLatestEntriesParams is parameters of getLatestEntries operation.
type GetLatestEntriesParams struct {
	// Filter entries by the last edited date.
	LastLastEditedAt OptDateTime
}

func unpackGetLatestEntriesParams(packed middleware.Parameters) (params GetLatestEntriesParams) {
	{
		key := middleware.ParameterKey{
			Name: "last_last_edited_at",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.LastLastEditedAt = v.(OptDateTime)
		}
	}
	return params
}

func decodeGetLatestEntriesParams(args [0]string, argsEscaped bool, r *http.Request) (params GetLatestEntriesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: last_last_edited_at.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "last_last_edited_at",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLastLastEditedAtVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotLastLastEditedAtVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.LastLastEditedAt.SetTo(paramsDotLastLastEditedAtVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "last_last_edited_at",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
