// Code generated by ogen, DO NOT EDIT.
package openapi

type CreateEntryRes interface {
	createEntryRes()
}

type DeleteEntryRes interface {
	deleteEntryRes()
}

type GetLinkedEntryPathsRes interface {
	getLinkedEntryPathsRes()
}

type UpdateEntryBodyRes interface {
	updateEntryBodyRes()
}

type UpdateEntryTitleRes interface {
	updateEntryTitleRes()
}

type UpdateEntryVisibilityRes interface {
	updateEntryVisibilityRes()
}
