/* tslint:disable */
/* eslint-disable */
/**
 * Entries API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmptyResponse
 */
export interface EmptyResponse {
    /**
     * 
     * @type {string}
     * @memberof EmptyResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the EmptyResponse interface.
 */
export function instanceOfEmptyResponse(value: object): value is EmptyResponse {
    return true;
}

export function EmptyResponseFromJSON(json: any): EmptyResponse {
    return EmptyResponseFromJSONTyped(json, false);
}

export function EmptyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmptyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function EmptyResponseToJSON(json: any): EmptyResponse {
    return EmptyResponseToJSONTyped(json, false);
}

export function EmptyResponseToJSONTyped(value?: EmptyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

