/* tslint:disable */
/* eslint-disable */
/**
 * Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntryWithDestTitle
 */
export interface EntryWithDestTitle {
    /**
     * 
     * @type {string}
     * @memberof EntryWithDestTitle
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithDestTitle
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithDestTitle
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithDestTitle
     */
    visibility: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithDestTitle
     */
    format: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithDestTitle
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntryWithDestTitle
     */
    dstTitle: string;
}

/**
 * Check if a given object implements the EntryWithDestTitle interface.
 */
export function instanceOfEntryWithDestTitle(value: object): value is EntryWithDestTitle {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('dstTitle' in value) || value['dstTitle'] === undefined) return false;
    return true;
}

export function EntryWithDestTitleFromJSON(json: any): EntryWithDestTitle {
    return EntryWithDestTitleFromJSONTyped(json, false);
}

export function EntryWithDestTitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryWithDestTitle {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'title': json['title'],
        'body': json['body'],
        'visibility': json['visibility'],
        'format': json['format'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'dstTitle': json['dstTitle'],
    };
}

export function EntryWithDestTitleToJSON(json: any): EntryWithDestTitle {
    return EntryWithDestTitleToJSONTyped(json, false);
}

export function EntryWithDestTitleToJSONTyped(value?: EntryWithDestTitle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'title': value['title'],
        'body': value['body'],
        'visibility': value['visibility'],
        'format': value['format'],
        'imageUrl': value['imageUrl'],
        'dstTitle': value['dstTitle'],
    };
}

