/* tslint:disable */
/* eslint-disable */
/**
 * Entries API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntryWithImage
 */
export interface EntryWithImage {
    /**
     * 
     * @type {string}
     * @memberof EntryWithImage
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithImage
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithImage
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithImage
     */
    visibility: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithImage
     */
    format: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithImage
     */
    imageUrl?: string | null;
}

/**
 * Check if a given object implements the EntryWithImage interface.
 */
export function instanceOfEntryWithImage(value: object): value is EntryWithImage {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    return true;
}

export function EntryWithImageFromJSON(json: any): EntryWithImage {
    return EntryWithImageFromJSONTyped(json, false);
}

export function EntryWithImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryWithImage {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'title': json['title'],
        'body': json['body'],
        'visibility': json['visibility'],
        'format': json['format'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
    };
}

export function EntryWithImageToJSON(json: any): EntryWithImage {
    return EntryWithImageToJSONTyped(json, false);
}

export function EntryWithImageToJSONTyped(value?: EntryWithImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'title': value['title'],
        'body': value['body'],
        'visibility': value['visibility'],
        'format': value['format'],
        'imageUrl': value['imageUrl'],
    };
}

