/* tslint:disable */
/* eslint-disable */
/**
 * Entries API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEntryBodyRequest
 */
export interface UpdateEntryBodyRequest {
    /**
     * The new content of the entry
     * @type {string}
     * @memberof UpdateEntryBodyRequest
     */
    body: string;
}

/**
 * Check if a given object implements the UpdateEntryBodyRequest interface.
 */
export function instanceOfUpdateEntryBodyRequest(value: object): value is UpdateEntryBodyRequest {
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function UpdateEntryBodyRequestFromJSON(json: any): UpdateEntryBodyRequest {
    return UpdateEntryBodyRequestFromJSONTyped(json, false);
}

export function UpdateEntryBodyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEntryBodyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function UpdateEntryBodyRequestToJSON(json: any): UpdateEntryBodyRequest {
    return UpdateEntryBodyRequestToJSONTyped(json, false);
}

export function UpdateEntryBodyRequestToJSONTyped(value?: UpdateEntryBodyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
    };
}

