/* tslint:disable */
/* eslint-disable */
/**
 * Entries API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEntryTitleRequest
 */
export interface UpdateEntryTitleRequest {
    /**
     * The new title for the entry
     * @type {string}
     * @memberof UpdateEntryTitleRequest
     */
    title: string;
}

/**
 * Check if a given object implements the UpdateEntryTitleRequest interface.
 */
export function instanceOfUpdateEntryTitleRequest(value: object): value is UpdateEntryTitleRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function UpdateEntryTitleRequestFromJSON(json: any): UpdateEntryTitleRequest {
    return UpdateEntryTitleRequestFromJSONTyped(json, false);
}

export function UpdateEntryTitleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEntryTitleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function UpdateEntryTitleRequestToJSON(json: any): UpdateEntryTitleRequest {
    return UpdateEntryTitleRequestToJSONTyped(json, false);
}

export function UpdateEntryTitleRequestToJSONTyped(value?: UpdateEntryTitleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
    };
}

