// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	admindb "github.com/tokuhirom/blog4/db/admin/admindb"
	gomock "go.uber.org/mock/gomock"
)

// MockEntryImageStore is a mock of EntryImageStore interface.
type MockEntryImageStore struct {
	ctrl     *gomock.Controller
	recorder *MockEntryImageStoreMockRecorder
	isgomock struct{}
}

// MockEntryImageStoreMockRecorder is the mock recorder for MockEntryImageStore.
type MockEntryImageStoreMockRecorder struct {
	mock *MockEntryImageStore
}

// NewMockEntryImageStore creates a new mock instance.
func NewMockEntryImageStore(ctrl *gomock.Controller) *MockEntryImageStore {
	mock := &MockEntryImageStore{ctrl: ctrl}
	mock.recorder = &MockEntryImageStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryImageStore) EXPECT() *MockEntryImageStoreMockRecorder {
	return m.recorder
}

// AdminGetEntryByPath mocks base method.
func (m *MockEntryImageStore) AdminGetEntryByPath(ctx context.Context, path string) (admindb.AdminGetEntryByPathRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetEntryByPath", ctx, path)
	ret0, _ := ret[0].(admindb.AdminGetEntryByPathRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetEntryByPath indicates an expected call of AdminGetEntryByPath.
func (mr *MockEntryImageStoreMockRecorder) AdminGetEntryByPath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetEntryByPath", reflect.TypeOf((*MockEntryImageStore)(nil).AdminGetEntryByPath), ctx, path)
}

// GetEntryImageByPath mocks base method.
func (m *MockEntryImageStore) GetEntryImageByPath(ctx context.Context, path string) (admindb.EntryImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntryImageByPath", ctx, path)
	ret0, _ := ret[0].(admindb.EntryImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntryImageByPath indicates an expected call of GetEntryImageByPath.
func (mr *MockEntryImageStoreMockRecorder) GetEntryImageByPath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntryImageByPath", reflect.TypeOf((*MockEntryImageStore)(nil).GetEntryImageByPath), ctx, path)
}

// InsertEntryImage mocks base method.
func (m *MockEntryImageStore) InsertEntryImage(ctx context.Context, arg admindb.InsertEntryImageParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEntryImage", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEntryImage indicates an expected call of InsertEntryImage.
func (mr *MockEntryImageStoreMockRecorder) InsertEntryImage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEntryImage", reflect.TypeOf((*MockEntryImageStore)(nil).InsertEntryImage), ctx, arg)
}
