name: E2E Tests

on:
  push:
    branches: [ main, develop, feat/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: blog4
          MYSQL_USER: blog4user
          MYSQL_PASSWORD: blog4password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -prootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      minio:
        image: minio/minio:latest
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl -f http://localhost:9000/minio/health/live"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install go-task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          sudo mv ./bin/task /usr/local/bin/

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: web/admin/pnpm-lock.yaml

      - name: Install TypeSpec dependencies
        run: pnpm install

      - name: Install sqlc
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/kyleconroy/sqlc/releases/download/v1.24.0/sqlc_1.24.0_linux_amd64.tar.gz
          sudo tar -xzf sqlc_1.24.0_linux_amd64.tar.gz -C /usr/local/bin sqlc

      - name: Generate code
        run: task gen

      - name: Setup database
        run: |
          mysql -h127.0.0.1 -uroot -prootpassword blog4 < db/schema.sql
          mysql -h127.0.0.1 -uroot -prootpassword blog4 < db/seed.sql
        env:
          MYSQL_HOST: 127.0.0.1

      - name: Install frontend dependencies
        working-directory: web/admin
        run: pnpm install

      - name: Build frontend
        working-directory: web/admin
        run: pnpm run build

      - name: Install Playwright
        working-directory: web/admin
        run: pnpm run test:e2e:install

      - name: Run E2E tests
        working-directory: web/admin
        run: pnpm run test:e2e
        env:
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 3306
          DATABASE_USER: blog4user
          DATABASE_PASSWORD: blog4password
          DATABASE_DB: blog4
          S3_ACCESS_KEY_ID: minioadmin
          S3_SECRET_ACCESS_KEY: minioadmin
          S3_REGION: us-east-1
          S3_ATTACHMENTS_BUCKET_NAME: blog4-attachments
          S3_BACKUP_BUCKET_NAME: blog4-backup
          S3_ENDPOINT: localhost:9000
          ADMIN_USER: admin
          ADMIN_PW: password
          LOCAL_DEV: true
          ALLOWED_ORIGINS: http://localhost:6174

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: web/admin/playwright-report/
          retention-days: 30